import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";

import { dmSerif, geistSans } from "@/app/ui/fonts";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <nav className="w-full py-2 border-b flex items-center px-6">
          <Link href="/" className="flex items-center gap-2">
            <Image src="/dormly.svg" alt="logo" width={36} height={36} />
            <h4 className={`${dmSerif.className} text-2xl`}>Dormly</h4>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
